<form action="#">
	<div id="RE_toolbar_container" style="border: 1px solid #CCC; width: 682px;display:none;">
		<div id="RE_toolbar">
			<a class="button html" action-type="toolbar_act" title="查看源码"
				command="html" unselectable="on"></a> <a class="button fontname"
				action-type="toolbar_act" title="字体" command="fontname"
				unselectable="on"></a> <a class="button fontsize"
				action-type="toolbar_act" title="字号" command="fontsize"
				unselectable="on"></a> <a class="button removeformat"
				action-type="toolbar_act" title="删除格式" command="removeformat"
				unselectable="on"></a> <a class="button bold"
				action-type="toolbar_act" title="粗体" command="bold"
				unselectable="on"></a> <a class="button italic"
				action-type="toolbar_act" title="斜体" command="italic"
				unselectable="on"></a> <a class="button underline"
				action-type="toolbar_act" title="下划线" command="underline"
				unselectable="on"></a> <a class="button strikethrough"
				action-type="toolbar_act" title="删除线" command="strikethrough"
				unselectable="on"></a> <a class="button justifyleft"
				action-type="toolbar_act" title="左对齐" command="justifyleft"
				unselectable="on"></a> <a class="button justifycenter"
				action-type="toolbar_act" title="居中" command="justifycenter"
				unselectable="on"></a> <a class="button justifyright"
				action-type="toolbar_act" title="右对齐" command="justifyright"
				unselectable="on"></a> <a class="button justifyfull"
				action-type="toolbar_act" title="两端对齐" command="justifyfull"
				unselectable="on"></a> <a class="button indent"
				action-type="toolbar_act" title="增加缩进" command="indent"
				unselectable="on"></a> <a class="button outdent"
				action-type="toolbar_act" title="减少缩进" command="outdent"
				unselectable="on"></a> <a class="button forecolor"
				action-type="toolbar_act" title="前景色" command="forecolor"
				unselectable="on"></a> <a class="button backcolor"
				action-type="toolbar_act" title="背景色" command="backcolor"
				unselectable="on"></a> <a class="button createlink"
				action-type="toolbar_act" title="超级连接" command="createlink"
				unselectable="on"></a> <a class="button insertimage"
				action-type="toolbar_act" title="插入图片" command="insertimage"
				unselectable="on"></a> <a class="button insertorderedlist"
				action-type="toolbar_act" title="有序列表" command="insertorderedlist"
				unselectable="on"></a> <a class="button insertunorderedlist"
				action-type="toolbar_act" title="无序列表" command="insertunorderedlist"
				unselectable="on"></a> <a class="button table"
				action-type="toolbar_act" title="表格" command="table"
				unselectable="on"></a> <a class="button emoticons"
				action-type="toolbar_act" title="表情" command="emoticons"
				unselectable="on"></a>
		</div>
		<iframe id="RE_iframe" frameborder="0"
			style="width: 100%; height: 300px;"></iframe>
		<textarea id="RE_textarea" wrap="on"
			style="display: none; width: 684px; height: 300px;">
		</textarea>
	</div>
</form>
