<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$ana_urls = array();
$ana_urls['0'] = array('name'=>'未知', 'tag'=>"default");
$ana_urls['1'] = array('name'=>'首页', 'tag'=>"home");
$ana_urls['2'] = array('name'=>'城市页', 'tag'=>"city");
$ana_urls['3'] = array('name'=>'商家页', 'tag'=>"shop");
$ana_urls['4'] = array('name'=>'品牌墙页', 'tag'=>"brandstreet");
$ana_urls['5'] = array('name'=>'地图模式页', 'tag'=>"citymap");
$ana_urls['6'] = array('name'=>'晒单页', 'tag'=>"dianping");
$ana_urls['7'] = array('name'=>'攻略列表页', 'tag'=>"shoptips_city");
$ana_urls['8'] = array('name'=>'折扣列表页', 'tag'=>"discount_city");
$ana_urls['9'] = array('name'=>'攻略详细页', 'tag'=>"shoptips_content");
$ana_urls['10'] = array('name'=>'折扣详细页', 'tag'=>"discount_content");
$ana_urls['11'] = array('name'=>'帮助', 'tag'=>"help");
$ana_urls['12'] = array('name'=>'友情链接', 'tag'=>"links");
$ana_urls['13'] = array('name'=>'sitemap', 'tag'=>"sitemap");
$ana_urls['14'] = array('name'=>'收藏', 'tag'=>"fav");
$ana_urls['15'] = array('name'=>'sorry', 'tag'=>"sorry");
$ana_urls['16'] = array('name'=>'优惠卷页', 'tag'=>"coupon_info");
$ana_urls['17'] = array('name'=>'注册', 'tag'=>"register");
$ana_urls['18'] = array('name'=>'下载coupon', 'tag'=>"download_coupon");
$ana_urls['19'] = array('name'=>'首页2', 'tag'=>"home_more");
$ana_urls['20'] = array('name'=>'后台', 'tag'=>"admin");
$ana_urls['21'] = array('name'=>'移动端', 'tag'=>"mobile");
$ana_urls['22'] = array('name'=>'折扣商店页面', 'tag'=>"discountshop");
$ana_urls['23'] = array('name'=>'回调weibo', 'tag'=>"callback_weibo");
$ana_urls['24'] = array('name'=>'回调qq', 'tag'=>"callback_qq");
$ana_urls['25'] = array('name'=>'个人信息页', 'tag'=>"myprofile");
$ana_urls['26'] = array('name'=>'商户下载', 'tag'=>"download_shop");
$ana_urls['27'] = array('name'=>'怎样到达', 'tag'=>"directions");
$ana_urls['28'] = array('name'=>'退出', 'tag'=>"logout");
$ana_urls['29'] = array('name'=>'锦囊', 'tag'=>"guide");

$ana_urls['400'] = array('name'=>'aj', 'tag'=>"aj");


$route = array();
$route['newyork'] = '1';
$route['losangeles'] = '2';
$route['chicago'] = '3';
$route['lasvegas'] = '4';
$route['sanfrancisco'] = '5';
$route['washington'] = '6';
$route['hawaii'] = '7';
$route['toronto'] = '8';
$route['vancouver'] = '9';
$route['boston'] = '10';
$route['houston'] = '11';
$route['dallas'] = '12';
$route['miami'] = '13';
$route['atlanta'] = '14';
$route['orlando'] = '15';
$route['sandiego'] = '16';
$route['philadelphia'] = '17';
$route['seattle'] = '18';
$route['montreal'] = '19';
$route['paris'] = '20';
$route['london'] = '21';
$route['milano'] = '22';
$route['roma'] = '23';
$route['venezia'] = '24';
$route['firenze'] = '25';
$route['berlin'] = '26';
$route['frankfurt'] = '27';
$route['munich'] = '28';
$route['barcelona'] = '29';
$route['madrid'] = '30';
$route['hamburg'] = '31';
$route['duesseldorf'] = '32';
$route['edinburgh'] = '33';
$route['liverpool'] = '34';
$route['manchester'] = '35';
$route['geneva'] = '36';
$route['zurich'] = '37';
$route['athens'] = '38';
$route['brussel'] = '39';
$route['luxembourg'] = '40';
$route['viena'] = '41';
$route['cardiff'] = '42';
$route['york'] = '43';
$route['hongkong'] = '44';
$route['macao'] = '45';
$route['taipei'] = '49';
$route['kaohsiung'] = '50';
$route['tokyo'] = '51';
$route['osaka'] = '52';
$route['nagoya'] = '53';
$route['dubai'] = '54';
$route['singapore'] = '55';
$route['dublin'] = '56';
$route['kobe'] = '57';
$route['kyoto'] = '58';
$route['beijing'] = '59';
$route['shanghai'] = '60';
$route['guangzhou'] = '61';
$route['shenzhen'] = '62';
$route['tianjin'] = '63';
$route['chongqing'] = '64';
$route['nanjing'] = '65';
$route['shenyang'] = '66';
$route['wuhan'] = '67';
$route['chengdu'] = '68';
$route['xian'] = '69';
$route['hangzhou'] = '70';
$route['dalian'] = '71';
$route['qingdao'] = '72';
$route['ningbo'] = '73';
$route['xiamen'] = '74';
$route['changsha'] = '75';
$route['dengzhou'] = '76';
$route['harbin'] = '77';
$route['jinan'] = '78';
$route['wuxi'] = '79';
$route['suzhou'] = '80';
$route['taiyuan'] = '81';
$route['changchun'] = '82';
$route['fuzhou'] = '83';
$route['urumqi'] = '84';
$route['kunming'] = '85';
$route['lanzhou'] = '86';
$route['nanchang'] = '87';
$route['guiyang'] = '88';
$route['nanning'] = '89';
$route['hefei'] = '90';
$route['shijiazhuang'] = '91';
$route['baotou'] = '92';
$route['hohhot'] = '93';
$route['haikou'] = '96';
$route['seoul'] = '97';

$config['my_route'] = $route;
$config['ana_urls'] = $ana_urls;


$ana_type_list = array(1=>"coupon统计");
$config['ana_type_list'] = $ana_type_list;


$spider_list = array();
$spider_list[1] = "http://www.baidu.com/search/spider.html";
$spider_list[2] = "http://www.google.com/bot.html";
$spider_list[3] = "http://www.linkdex.com/bots/";
$spider_list[4] = "http://www.bing.com/bingbot.htm";
$spider_list[5] = "360Spider";
$spider_list[6] = "YisouSpider";
$spider_list[7] = "webmeup-crawle";
$spider_list[8] = "http://ahrefs.com/robot/";
$spider_list[9] = "http://www.easou.com/search/spider.html";
$spider_list[10] = "http://www.opensiteexplorer.org/dotbot";
$spider_list[11] = "NetcraftSurveyAgent";
$spider_list[12] = "http://www.majestic12.co.uk/bot.php";
$spider_list[13] = "www.skimlinks.com";

$spider_list[99] = "robot";
$spider_list[100] = "Nutch";
$spider_list[101] = "nutch";
$spider_list[102] = "spider";
$spider_list[103] = "Googlebot";
$spider_list[104] = "Yahoo! Slurp";
$spider_list[105] = "YodaoBot";
$spider_list[106] = "msnbot";
$spider_list[107] = "Crawler";
$spider_list[108] = "YandexBot";
$config['spider_list'] = $spider_list;

